/* PixelForge — exporters: PNG pages / atlas JSON / CSS / GIF / ZIP (v1.1) */
(function () {
  "use strict";

  function uniqueNames(names) {
    const seen = new Map();
    return names.map((n) => {
      const base = (n || "frame").replace(/[^\w\-. ]+/g, "_").trim() || "frame";
      const c = seen.get(base) || 0;
      seen.set(base, c + 1);
      return c === 0 ? base : `${base}_${c + 1}`;
    });
  }

  function pageNames(sheet, metaName) {
    if (sheet.pagesCount <= 1) return [`${metaName}.png`];
    return sheet.pages.map((_, i) => `${metaName}_p${i + 1}.png`);
  }

  function rects(sheet) {
    const names = uniqueNames(sheet.frames.map((f) => f.name));
    return sheet.frames.map((f, i) => ({
      name: names[i],
      page: f.page || 0,
      x: f.x, y: f.y, w: f.w, h: f.h,
      offX: f.offX, offY: f.offY,
      srcW: f.srcW, srcH: f.srcH,
      fullW: f.fullW, fullH: f.fullH,
      pivot: f.pivot,
    }));
  }

  function buildAtlas(fmt, sheet, metaName) {
    const P = PF.state.params;
    const rs = rects(sheet);
    const images = pageNames(sheet, metaName);

    if (fmt === "generic") {
      const frames = {};
      for (const r of rs) {
        frames[r.name] = {
          frame: { x: r.x, y: r.y, w: r.w, h: r.h },
          rotated: false,
          trimmed: r.srcW !== r.fullW || r.srcH !== r.fullH,
          spriteSourceSize: { x: r.offX, y: r.offY, w: r.srcW, h: r.srcH },
          sourceSize: { w: r.fullW, h: r.fullH },
          pivot: { x: r.pivot.x, y: r.pivot.y },
          ...(sheet.pagesCount > 1 ? { textureIndex: r.page } : {}),
        };
      }
      return JSON.stringify({
        meta: {
          app: "PixelForge",
          version: "1.1.0",
          image: images[0],
          images,
          size: { w: sheet.width, h: sheet.height },
          scale: String(P.sheet.scale),
        },
        frames,
      }, null, 2);
    }

    if (fmt === "phaser") {
      const textures = sheet.pages.map((p, pi) => ({
        image: images[pi],
        format: "",
        size: { w: p.width, h: p.height },
        scale: String(P.sheet.scale),
        frames: rs.filter((r) => r.page === pi).map((r) => ({
          filename: r.name,
          frame: { x: r.x, y: r.y, w: r.w, h: r.h },
          rotated: false,
          trimmed: r.srcW !== r.fullW || r.srcH !== r.fullH,
          spriteSourceSize: { x: r.offX, y: r.offY, w: r.srcW, h: r.srcH },
          sourceSize: { w: r.fullW, h: r.fullH },
          pivot: { x: r.pivot.x, y: r.pivot.y },
        })),
      }));
      return JSON.stringify({ textures }, null, 2);
    }

    if (fmt === "aseprite") {
      const duration = Math.max(1, Math.round(1000 / P.preview.fps));
      const frames = rs.map((r) => ({
        filename: `${r.name}.png`,
        frame: { x: r.x, y: r.y, w: r.w, h: r.h },
        rotated: false,
        trimmed: r.srcW !== r.fullW || r.srcH !== r.fullH,
        spriteSourceSize: { x: r.offX, y: r.offY, w: r.srcW, h: r.srcH },
        sourceSize: { w: r.fullW, h: r.fullH },
        duration,
        ...(sheet.pagesCount > 1 ? { textureIndex: r.page } : {}),
      }));
      return JSON.stringify({
        frames,
        meta: {
          app: "PixelForge",
          version: "1.1.0",
          image: images[0],
          images,
          format: "RGBA8888",
          size: { w: sheet.width, h: sheet.height },
          scale: "1",
          frameTags: [],
        },
      }, null, 2);
    }

    if (fmt === "css") {
      const cls = metaName.replace(/[^\w-]/g, "-");
      const lines = [
        `/* Generated by PixelForge — ${images.join(", ")} */`,
        `.${cls} { background-repeat: no-repeat; image-rendering: pixelated; display: inline-block; }`,
        "",
      ];
      for (const r of rs) {
        lines.push(
          `.${cls}-${r.name.replace(/[^\w-]/g, "_")} {` +
          ` width: ${r.w}px; height: ${r.h}px;` +
          ` background-image: url("${images[r.page]}");` +
          ` background-position: -${r.x}px -${r.y}px; }`
        );
      }
      return lines.join("\n") + "\n";
    }

    throw new Error("unknown format " + fmt);
  }

  /* ---------- downloads ---------- */

  function saveBlob(name, blob) {
    const a = document.createElement("a");
    const url = URL.createObjectURL(blob);
    a.href = url;
    a.download = name;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 4000);
  }

  function saveText(name, text, mime) {
    saveBlob(name, new Blob([text], { type: mime || "text/plain" }));
  }

  function canvasPngBytes(canvas) {
    return new Promise((resolve, reject) => {
      canvas.toBlob(async (blob) => {
        if (!blob) return reject(new Error("png encode failed"));
        resolve(new Uint8Array(await blob.arrayBuffer()));
      }, "image/png");
    });
  }

  /* ---------- PNG sheet (all pages) ---------- */

  async function exportSheet() {
    const sheet = PF.ensureSheet();
    if (!sheet) return PF.toast("Nothing to export — import frames first.");
    const name = PF.state.params.export.name || "sprites";
    const names = pageNames(sheet, name);
    for (let i = 0; i < sheet.pages.length; i++) {
      saveBlob(names[i], new Blob([await canvasPngBytes(sheet.pages[i].canvas)], { type: "image/png" }));
    }
    PF.status(`Exported ${sheet.pages.length} sheet PNG${sheet.pages.length > 1 ? "s" : ""} (${sheet.width}×${sheet.height})`);
  }

  async function exportAtlas() {
    const sheet = PF.ensureSheet();
    if (!sheet) return PF.toast("Nothing to export — import frames first.");
    const fmt = PF.state.params.export.format;
    const name = PF.state.params.export.name || "sprites";
    if (fmt === "css") saveText(`${name}.css`, buildAtlas("css", sheet, name), "text/css");
    else saveText(`${name}.json`, buildAtlas(fmt, sheet, name), "application/json");
    PF.status(`Exported ${name}.${fmt === "css" ? "css" : "json"} (${fmt})`);
  }

  /* ---------- individual frames ---------- */

  async function frameCanvas(f) {
    const c = document.createElement("canvas");
    c.width = f.w; c.height = f.h;
    const ctx = c.getContext("2d");
    ctx.imageSmoothingEnabled = false;
    const src = PF.state.frames.find((x) => x.id === f.id);
    if (!src || !src.proc) return null;
    ctx.drawImage(src.proc, f.offX, f.offY, f.srcW, f.srcH, 0, 0, f.w, f.h);
    return c;
  }

  async function exportFramesZip() {
    const sheet = PF.ensureSheet();
    if (!sheet) return PF.toast("Nothing to export — import frames first.");
    const name = PF.state.params.export.name || "sprites";
    const names = uniqueNames(sheet.frames.map((f) => f.name));
    const entries = [];
    for (let i = 0; i < sheet.frames.length; i++) {
      const c = await frameCanvas(sheet.frames[i]);
      if (!c) continue;
      entries.push({ name: `frames/${names[i]}.png`, data: await canvasPngBytes(c) });
    }
    saveBlob(`${name}_frames.zip`, PF.makeZip(entries));
    PF.status(`Exported ${entries.length} frames as ZIP.`);
  }

  /* ---------- animated GIF ---------- */

  async function exportGif() {
    const sheet = PF.ensureSheet();
    if (!sheet || !sheet.frames.length) return PF.toast("Nothing to export — import frames first.");
    if (!window.PFGif) return PF.toast("GIF encoder not loaded.");

    const P = PF.state.params;
    const name = P.export.name || "sprites";
    const placed = PF.state.frames.map((f) => {
      const p = sheet.frames.find((s) => s.id === f.id);
      return { f, p };
    }).filter((x) => x.p);

    // uniform canvas = max cell size
    const W = Math.max(...placed.map((x) => x.p.w));
    const H = Math.max(...placed.map((x) => x.p.h));

    const datas = [];
    for (const { p } of placed) {
      const c = await frameCanvas(p);
      const ctx = c.getContext("2d", { willReadFrequently: true });
      const img = ctx.getImageData(0, 0, W, H);
      // normalize semi-transparent pixels + copy into a plain same-realm Uint8Array
      const d = img.data;
      const out = new Uint8Array(W * H * 4);
      for (let i = 0; i < d.length; i += 4) {
        if (d[i + 3] < 128) { out[i] = 0; out[i + 1] = 0; out[i + 2] = 0; out[i + 3] = 0; }
        else { out[i] = d[i]; out[i + 1] = d[i + 1]; out[i + 2] = d[i + 2]; out[i + 3] = 255; }
      }
      datas.push(out);
    }

    // one shared palette across frames (keeps colors stable)
    let sample = null;
    if (datas.length === 1) sample = datas[0];
    else {
      sample = new Uint8Array(datas.reduce((s, i) => s + i.length, 0));
      let o = 0;
      for (const im of datas) { sample.set(im, o); o += im.length; }
    }
    const palette = PFGif.quantize(sample, 255, { format: "rgba4444", oneBitAlpha: true });
    const transparentIndex = palette.findIndex((c) => c.length > 3 && c[3] === 0);
    const hasTransparency = transparentIndex >= 0;

    const gif = PFGif.GIFEncoder();
    const defaultDelay = Math.max(20, Math.round(1000 / P.preview.fps));
    datas.forEach((data, i) => {
      const index = PFGif.applyPalette(data, palette, "rgba4444");
      const opts = {
        delay: (placed[i].f.delay || defaultDelay),
        transparent: hasTransparency,
        transparentIndex: hasTransparency ? Math.max(0, transparentIndex) : 0,
      };
      if (i === 0) {
        opts.palette = palette;
        opts.repeat = P.preview.mode === "once" ? -1 : 0;
      }
      gif.writeFrame(index, W, H, opts);
    });
    gif.finish();

    saveBlob(`${name}.gif`, new Blob([gif.bytes()], { type: "image/gif" }));
    PF.status(`Exported ${name}.gif (${W}×${H}, ${datas.length} frames)`);
  }

  /* ---------- ZIP (everything) ---------- */

  async function exportEverything() {
    const sheet = PF.ensureSheet();
    if (!sheet) return PF.toast("Nothing to export — import frames first.");
    const fmt = PF.state.params.export.format;
    const name = PF.state.params.export.name || "sprites";
    const entries = [];
    const images = pageNames(sheet, name);

    for (let i = 0; i < sheet.pages.length; i++) {
      entries.push({ name: images[i], data: await canvasPngBytes(sheet.pages[i].canvas) });
    }

    if (fmt === "css") entries.push({ name: `${name}.css`, data: enc(buildAtlas("css", sheet, name)) });
    else entries.push({ name: `${name}.json`, data: enc(buildAtlas(fmt, sheet, name)) });

    if (fmt !== "generic") {
      entries.push({ name: `${name}.generic.json`, data: enc(buildAtlas("generic", sheet, name)) });
    }

    // animated preview gif
    try {
      const prevFmt = PF.state.params.export.format;
      const gifBytes = await buildGifBytes(sheet, name);
      if (gifBytes) entries.push({ name: `${name}.gif`, data: gifBytes });
      void prevFmt;
    } catch (e) { console.warn("gif skipped", e); }

    entries.push({
      name: "README.txt",
      data: enc(
`PixelForge export
=================
${images.join("\n")} — sprite sheet(s) (${sheet.pages.length} page(s), page0 ${sheet.width}×${sheet.height})
${fmt === "css" ? `${name}.css` : `${name}.json`} — atlas data (${fmt})
${fmt !== "generic" ? `${name}.generic.json — generic atlas\n` : ""}${name}.gif — animated preview
Scale: ${PF.state.params.sheet.scale}× · Padding: ${PF.state.params.sheet.padding}px
Preview FPS: ${PF.state.params.preview.fps}
Pivot points are exported (px, relative to each trimmed frame).

Generated offline by PixelForge
`)
    });

    saveBlob(`${name}_pixelforge.zip`, PF.makeZip(entries));
    PF.status(`Exported ZIP with ${entries.length} files.`);
  }

  /** GIF bytes without downloading (for ZIP inclusion). */
  async function buildGifBytes(sheet, name) {
    void name;
    if (!window.PFGif || !sheet.frames.length) return null;
    const P = PF.state.params;
    const placed = PF.state.frames.map((f) => ({ f, p: sheet.frames.find((s) => s.id === f.id) })).filter((x) => x.p);
    const W = Math.max(...placed.map((x) => x.p.w));
    const H = Math.max(...placed.map((x) => x.p.h));
    const datas = [];
    for (const { p } of placed) {
      const c = await frameCanvas(p);
      const ctx = c.getContext("2d", { willReadFrequently: true });
      const img = ctx.getImageData(0, 0, W, H);
      const d = img.data;
      const out = new Uint8Array(W * H * 4);
      for (let i = 0; i < d.length; i += 4) {
        if (d[i + 3] < 128) { out[i] = 0; out[i + 1] = 0; out[i + 2] = 0; out[i + 3] = 0; }
        else { out[i] = d[i]; out[i + 1] = d[i + 1]; out[i + 2] = d[i + 2]; out[i + 3] = 255; }
      }
      datas.push(out);
    }
    let sample = null;
    if (datas.length === 1) sample = datas[0];
    else {
      sample = new Uint8Array(datas.reduce((s, i) => s + i.length, 0));
      let o = 0;
      for (const im of datas) { sample.set(im, o); o += im.length; }
    }
    const palette = PFGif.quantize(sample, 255, { format: "rgba4444", oneBitAlpha: true });
    const transparentIndex = palette.findIndex((c) => c.length > 3 && c[3] === 0);
    const hasTransparency = transparentIndex >= 0;
    const gif = PFGif.GIFEncoder();
    const defaultDelay = Math.max(20, Math.round(1000 / P.preview.fps));
    datas.forEach((data, i) => {
      const index = PFGif.applyPalette(data, palette, "rgba4444");
      const opts = {
        delay: placed[i].f.delay || defaultDelay,
        transparent: hasTransparency,
        transparentIndex: Math.max(0, transparentIndex),
      };
      if (i === 0) { opts.palette = palette; opts.repeat = P.preview.mode === "once" ? -1 : 0; }
      gif.writeFrame(index, W, H, opts);
    });
    gif.finish();
    return gif.bytes();
  }

  function enc(s) { return new TextEncoder().encode(s); }

  window.PF = window.PF || {};
  Object.assign(window.PF, {
    buildAtlas, pageNames,
    exportSheet, exportAtlas, exportFramesZip, exportGif, exportEverything,
    saveText,
  });
})();
